### ISSUE TITLE
Support for php v 8.1

### ISSUE THREAD

**Issue by gormur** [leth/PHP-IPAddress#32]
Hi
There is a few issues that prevents proper support for php v 8.1. I have made a fork with minimal changes, but I'd be happy to contribute here. I would then suggest a v 2.0.0 as backwards comparability will be broken. Just writing this issue to test if there is activity in the project.

**Comment by leth** [comment]
Hello! I don't check here often, I don't do any PHP these days!
Wow PHP has changed a lot! A major version bump sounds like a good plan. I'd be happy to review a PR!

**Comment by leth** [comment]
To summarize from #33:

- A major version bump was deemed necessary as the upgrade will break compatibility
- a 2.0-dev branch has been created
- the code & CI config has been updated to work in 8.1+

I'm not really doing any PHP these days, so I don't know if the release is now ready, or if there are more changes worth making to make it idiomatic modern PHP. I'll have to leave that to @tabacco & others I'm afraid!

**Comment by tabacco** [comment]
I've opened https://github.com/leth/PHP-IPAddress/pull/36 to start the ball rolling on releasing 2.0.0 with PHP8 support.

**Comment by gormur** [comment]
Closing this now as #36 has been merged
