### ISSUE TITLE
Merge CIDR functionality

### ISSUE THREAD

**Issue by nyurik** [leth/PHP-IPAddress#6]
I have been looking for CIDR merge functionality for PHP, but apparently noone has it yet.

Python has a good library - https://github.com/drkjam/netaddr/blob/rel-0.7.x/netaddr/ip/__init__.py#L1558  that implements it, together with all the unit tests. If you have some spare time, please implement. Thanks!!! :)

**Comment by MikeRegex** [comment]
Hello, you can try it merge_cidr($your_array);

`<?php function merge_cidr(array $cidr_or_ipv4_list){
foreach($cidr_or_ipv4_list as $a)
if ($b=strpos($a,'/'))
$c[(int)substr($a,1+$b)][]=ip2long(substr($a,0,$b));
else $c[32][]=ip2long($a);
$c=merge_cidr_summarize($c);
foreach($c as $d=>&$e)
$e=array_map(function(int$a) use($d){return [$a,$a+(1<<(32-$d))-1];},$e);
foreach($c as $f=>$g)
foreach($c as $h=>$i)
if($f>$h)
foreach($g as $j=>$k)
foreach($i as $l)
if ($k[0]>=$l[0] && $k[1]<=$l[1])
unset($c[$f][$j]);
foreach($c as $f=>$g)
foreach($g as $h) $z[]=long2ip($h[0]).'/'.$f;
return array_reverse($z);
}

function merge_cidr_summarize(array $a){
$b=false;
$c=[];
krsort($a);
foreach($a as $d => $e){
sort($a[$d]);
$k=count($a[$d]);
for($i=0;$i<$k;$i++)
if($a[$d][$i]==$a[$d][$i+1]) continue;
elseif(($a[$d][$i]&(-1<<33-$d))==($a[$d][$i+1]&(-1<<33-$d))){
$c[$d-1][]=$a[$d][$i++]&(-1<<33-$d);
$b=true;
}
else $c[$d][]=$a[$d][$i];
}
return $b?merge_cidr_summarize($c):$a;
}`

**Comment by leth** [comment]
Holy loops batman! There's a lot of them in there!
I should probably add something to the README to cover the 'merge' feature.

**Comment by MikeRegex** [comment]
hi, can you modify the regex to #^[^0-9]*$valid_ip(?:/$valid_routing_prefix)?[^0-9]*$#  on your edit please

**Comment by leth** [comment]
I'll just leave your version, so you can edit it.
